FROM node:lts-alpine as builder

RUN apk --no-cache add curl

WORKDIR /app
RUN mkdir UPLOADS_DIR

COPY tsconfig.json tsconfig.json

COPY package.json package.json

RUN npm i
RUN npm install -g typescript

COPY src src

RUN tsc

FROM node:lts-alpine

RUN apk --no-cache add curl

WORKDIR /app

COPY --from=builder /app/dist /app/dist

COPY package.json package.json

RUN npm install --production

CMD npm run startprod