name: jest-and-docker-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto frontend and run tests
        run: cd frontend && npm i && npm test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Copy production env file
        run: echo "${{ secrets.PRODUCTION_ENV_FILE }}" > .env.production
      - name: Goto e2e and run tests
        run: docker compose -f docker-compose.e2e.yml up --build --exit-code-from e2e

  docker:
    needs: test-front
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildtransfer:latest
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:backend"
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildtransfer:latest
      - name: Build and push files
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:files"
          file: Dockerfile.prod
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildtransfer:latest
